name: Run benchmarks on NVIDIA GPU backend

on: pull_request

jobs:
  benchmark-nvidia-gpu:
    strategy:
      matrix:
        runner:
          - cms-patatrack-h100
          - cms-patatrack-l40s
    runs-on: ${{ matrix.runner }}
    container: registry.cern.ch/ngt/lxplus-like:9

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: |
        dnf install epel-release -y
        dnf makecache -y
        dnf install -y google-benchmark google-benchmark-devel

    - name: Compile and run benchmark
      working-directory: ${{ github.workspace }}/benchmark/dataset_size
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel --verbose
        echo "Running serial backend"
        ./build/serial.out
        echo "Running OpenMP backend"
        ./build/openmp.out
        echo "Running CUDA backend"
        ./build/cuda.out
