name: GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: main

      - name: Switch to gh-pages branch and rebase
        run: |
          git fetch
          git checkout gh-pages
          git reset --hard main

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@edge

      - name: Install sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx breathe sphinx_immaterial sphinx-rtd-theme recommonmark

      - name: Build Python modules
        run: |
          cmake -B build -DBUILD_PYTHON=ON
          cmake --build build --parallel

      - name: Build Documentation
        working-directory: ${{ github.workspace }}/docs
        run: |
          make html
          mv build/html/* ./

      - name: Set up git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        
      - name: Switch to gh-pages branch and rebase
        run: |
          git add ./docs --force
          git commit -m "Auto-deploy documentation"
          git push origin gh-pages --force
