name: GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: main

      - name: Switch to gh-pages branch and rebase
        if: github.event_name == 'push'
        run: |
          git fetch
          git checkout gh-pages
          git reset --hard main

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@edge

      - name: Install dependencies
        run: | 
          sudo apt install -y libboost-atomic-dev
          python -m pip install --upgrade pip
          python -m pip install scikit-learn pandas matplotlib


      - name: Install sphinx
        run: |
          pip install 'sphinx<9.0' breathe sphinx_immaterial sphinx-rtd-theme recommonmark

      - name: Build Python modules
        run: |
          cmake -B build -DBUILD_PYTHON=ON
          cmake --build build --parallel

      - name: Build Documentation
        working-directory: ${{ github.workspace }}/docs
        run: |
          make html
          mv build/html/* ./

      - name: Set up git
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        
      - name: Switch to gh-pages branch and rebase
        if: github.event_name == 'push'
        run: |
          git add ./docs --force
          git commit -m "Auto-deploy documentation"
          git push origin gh-pages --force
