name: Test installation of the Python library

# The workflow gets triggered by pushes and pull requests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cxx-installation:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install docker
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      - name: Test installation inside docker containers (serial)
        working-directory: ${{github.workspace}}/docker/serial
        run: |
          ls
          docker build -t serial .

          docker run -t -v "$(pwd)"/../../:/app serial bash -c \
            "cd /app && pip install .;
            python3 -c 'import CLUEstering' || exit 0"

      - name: Test installation inside docker containers (serial without boost)
        working-directory: ${{github.workspace}}/docker/no_boost
        run: |
          docker build -t noboost .

          docker run -t -v "$(pwd)"/../../:/app noboost bash -c \
            "cd /app && pip install .;
            python3 -c 'import CLUEstering' || exit 0"

      - name: Test installation inside docker containers (tbb)
        working-directory: ${{github.workspace}}/docker/tbb
        run: |
          docker build -t tbb .

          docker run -t -v "$(pwd)"/../../:/app tbb bash -c \
            "cd /app && pip install .;
            python3 -c 'import CLUEstering' || exit 0"

      - name: Test installation inside docker containers (without gcc)
        working-directory: ${{github.workspace}}/docker/no_gcc
        run: |
          docker build -t nogcc .

          docker run -t -v "$(pwd)"/../../:/app nogcc bash -c \
            "cd /app && pip install .;
            python3 -c 'import CLUEstering' || exit 0"

      - name: Test installation inside docker containers (without cmake)
        working-directory: ${{github.workspace}}/docker/no_cmake
        run: |
          docker build -t nocmake .

          docker run -t -v "$(pwd)"/../../:/app nocmake bash -c \
            "cd app && pip install .;
            python3 -c 'import CLUEstering' || exit 0"
