name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-clang-15
            os: ubuntu-latest
            container: fedora:42
            compiler: clang-15
          - name: linux-clang-17
            os: ubuntu-latest
            container: fedora:42
            compiler: clang-17
          - name: linux-clang-18
            os: ubuntu-latest
            container: fedora:42
            compiler: clang-18
          - name: linux-clang-19
            os: ubuntu-latest
            container: fedora:42
            compiler: clang-19
          - name: macos-clang
            os: macos-latest
          - name: windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
    - name: Install dependencies
      if: matrix.container == 'fedora:42'
      run: |
        dnf install -y ${{ matrix.compiler }}
        dnf install -y git cmake boost-devel tbb libomp.x86_64 python3-devel python3-pip

    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install boost tbb libomp

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up vcpkg
      if: matrix.os == 'windows-latest'
      run: |
        echo "VCPKG_ROOT=C:/vcpkg" >> $env:GITHUB_ENV
        echo "CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }}
      if: matrix.os == 'macos-latest'
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      if: matrix.os != 'windows-latest'
      run: |
        python3 -m pip install --upgrade pip --break-system-packages
        python3 -m pip install pytest scikit-learn pandas matplotlib --break-system-packages

    - name: Install Python dependencies
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest scikit-learn pandas matplotlib

    - name: Compile CLUEstering modules
      if: matrix.os != 'windows-latest'
      working-directory: ${{ github.workspace }}
      run: |
        cmake -S . -B build -DBUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel

    - name: Compile CLUEstering modules
      if: matrix.os == 'windows-latest'
      working-directory: ${{ github.workspace }}
      run: |
        cmake -S . -B build -DBUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$env:CMAKE_TOOLCHAIN_FILE" -DVCPKG_TARGET_TRIPLET=x64-windows
        cmake --build build --parallel --config Release

    - name: Run tests of the Python library
      if: matrix.os != 'windows-latest'
      working-directory: ${{github.workspace}}/tests
      run: |
        python3 -m pytest ./*.py

    - name: Run tests of the Python library
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/tests
      run: |
        python -m pytest *.py
