name: Compile and run tests on NVIDIA GPUs

on: pull_request

jobs:
  run-tests:
    strategy:
      matrix:
        runner:
          - cms-patatrack-h100
          - cms-patatrack-l40s
    runs-on: ${{ matrix.runner }}
    container: registry.cern.ch/ngt/lxplus-like:9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install alpaka
        run: |
          wget https://github.com/alpaka-group/alpaka/archive/refs/tags/2.1.1.tar.gz
          tar -xzf 2.1.1.tar.gz && cd alpaka-2.1.1
          cmake -B build -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo cmake --install build

      - name: Compile and run benchmark
        working-directory: ${{ github.workspace }}
        run: |
          cmake -B build -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel -v
          ctest --test-dir build/cuda --output-on-failure
